---
  apiVersion: apps/v1
  kind: Deployment
  metadata:
     name: mydeploy
  spec:
     replicas: 3
     selector:
        matchLabels:
           name: vijay
     template:
        metadata:
           labels:
              name: vijay
        spec:
           containers:
              - name: cont-1
                image: shaikmustafa/dm
                ports:
                   - containerPort: 80
                     
